version: '3'

services:
  flask-app:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '5000:5000'

  mongo:
    image: mongo:3.4
    restart: always
    hostname: 'mongo'
    volumes: 
      - db_data_mongo:/data/db
    ports:
      - "27018:27017"

volumes:
  db_data_mongo: